### ISSUE TITLE
Changing images URL

### ISSUE THREAD

**Issue by felipesuri** [adapttive/vue-markdown#15]
I'm developing a new blog with Strapi + Gridsome. I get my markdown from an external API (Strapi) and I need change the images URL.

My API return an image url like this `/uploads/image.png`, but I need add the API URL, like `strapi.felipesuri.com/uploads/image.png`.

My idea is implement an prop (not required) and I pass the API URL, like:

```vue
<template>
  <VueMarkdown :source="article.content" imagesUrl="http://localhost:1338" />
</template>
```

**Comment by milindsingh** [comment]
There can be better ways:
1. Use [cloudinary.com](https://cloudinary.com/invites/lpov9zyyucivvxsnalc5/wez610gzb0sfcnot2ku5) for storing images and integrate cloudinary plugin in strapi to deliver complete url images in markdown
2. Use gridsome strapi plugin to pull all media content during build and reder it from frontend hosting like netlify
3. Write a custom plugin for vue-markdown to modify image urls like in [adapttive/markdown-it-external-preview](https://github.com/adapttive/markdown-it-external-preview) and inject it like explained in https://github.com/adapttive/vue-markdown#plugins
