### ISSUE TITLE
HMR fails when using Vite due to Node globals

### ISSUE THREAD

**Issue by juhasev** [adapttive/vue-markdown#17]
Hi there, 

Just switched from webpack to Vite and this error comes up in HMR mode. There seems to be no way to polyfill node globals in this mode. Looks like some code is assuming we are running this in pure Node environment. We have over 10 places where your package is used!

vue-markdown.common.js:2 Uncaught ReferenceError: global is not defined
    at node_modules/@adapttive/vue-markdown/dist/vue-markdown.common.js (vue-markdown.common.js:2:1210)

Any ideas how to resolve this?

Thanks, Juha

**Comment by bblumenfelder** [comment]
Did you resolve this?

**Comment by juhasev** [comment]
Yes, but it has been so long, I don't remember how but it is solvable. I would try this. Create a new project with Vue CLI and attempt to use vue-markdown. Compare the Vite config to yours.

**Comment by bblumenfelder** [comment]
I resolved it by importing the Vue-Component directly:

`import VueMarkdown from '@adapttive/vue-markdown/src/VueMarkdown.js'`
