### ISSUE TITLE
Update instructions for installing and using the package

### ISSUE THREAD

**Issue by MichaelCurrin** [adapttive/vue-markdown#8]
The docs are out of date since forking.

The simplest is to use the name as it appears in package.json

```json
{
  "dependencies": {
  "@adapttive/vue-markdown": "^X.X.X"
  }
}
```
So then the README would say:

```sh
npm install @adapttive/vue-markdown
```
Then
```js
import VueMarkdown '@adapttive/vue-markdown'
```

**Comment by MichaelCurrin** [comment]
If migrating from `vue-markdown`, it is plain enough that one has to do a find-and-replace to achieve the import correctly.

**Comment by MichaelCurrin** [comment]
Just to mention another approach is installing this as a replacement as an alias so it appears as `"vue-markdown": "npm:@adapttive/vue-markdown@^X.X.X"` in the package.json. And one doesn't have to find-and-replace the imports if migrating.

```sh
npm i vue-markdown@npm:@adapttive/vue-markdown
```
That is more complex (it took me a while to figure out the syntax).

So I would think the first solution above is cleaner and works well enough for someone as a first time user or migrating.

**Comment by MichaelCurrin** [comment]
I'm happy to make the changes after agreement

**Comment by milindsingh** [comment]
Thanks @MichaelCurrin I have updated few things in README.md just create PR for anything needed to be updated.

**Comment by MichaelCurrin** [comment]
Thanks, README.md looks good

BTW `--save` is no longer needed unless you have an old version of NPM or Yarn. It is implied.
