### ISSUE TITLE
Address network privileges request

### ISSUE THREAD

**Issue by MichaelCurrin** [adapttive/vue-markdown#9]
Hi. I've been using the beta version `3.0.0-beta.2`. My tests were passing.

I then upgraded to `3.0.3`. Then when I ran tests, my Mac asked me to accept incoming network requests. That seemed weird so I clicked Deny.

That causes my tests to fail.

```
Time:        4.985 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

So the recent code changes seem mostly to be around dependencies and version numbers - do you know what caused the issue and if it acceptable?

**Comment by milindsingh** [comment]
@MichaelCurrin need to check, updated a lot of dependencies.

**Comment by MichaelCurrin** [comment]
Thanks.

**Comment by milindsingh** [comment]
Fixed with 4.X.X release.
